__default__:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 5
  mem: "10gb"
  walltime: "04:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

fastp_qc:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 5
  mem: "5gb"
  walltime: "04:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

split_rg:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 1
  mem: "3gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

alignment:
  jobname: "{rule}_{wildcards.sample}_{wildcards.flowcell}_{wildcards.lane}"
  nodes: 1
  ppn: 15
  mem: "20gb"
  walltime: "12:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

sort_bam:
  jobname: "{rule}_{wildcards.sample}_{wildcards.flowcell}_{wildcards.lane}"
  nodes: 1
  ppn: 10
  mem: "3gb"
  walltime: "04:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

merge_bam:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 10
  mem: "10gb"
  walltime: "12:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

set_tag:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 1
  mem: "3gb"
  walltime: "12:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

mark_duplicate:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 1
  mem: "50gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

gatk_baserecalibrator:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 1
  mem: "8gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

apply_BQSR:
  jobname: "{rule}_{wildcards.sample}"
  nodes: 1
  ppn: 1
  mem: "12gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

haplotype_caller:
  jobname: "{rule}_{wildcards.sample}_{wildcards.chromosome}"
  nodes: 1
  ppn: 1
  mem: "12gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

GenomicsDB_import:
  jobname: "{rule}_{wildcards.chromosome}"
  nodes: 1
  ppn: 1
  mem: "4gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"

Joint_Genotyping:
  jobname: "{rule}_{wildcards.chromosome}"
  nodes: 1
  ppn: 1
  mem: "4gb"
  walltime: "24:00:00"
  queue: "short"
  email: "Zih-Hua.Fang@dzne.de"
  mailon: "n"
  jobout: "oe"
  outdir: "logs/"
