#cluster: "pbs-submit.py"
#cluster-status: "pbs-status.py"
#jobscript: "pbs-jobscript.sh"
cluster-config: "pbs-torque/cluster_config.yml"
cluster: "qsub -N {cluster.jobname} -l nodes={cluster.nodes}:ppn={cluster.ppn},mem={cluster.mem},walltime={cluster.walltime} -q {cluster.queue} -M {cluster.email} -m {cluster.mailon} -j {cluster.jobout} -o {cluster.outdir} -V"
jobs: 100
immediate-submit: False
verbose: True
notemp: True
local-cores: 1
latency-wait: 60
use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-singularity: True
