# This is the config for retrieving CADD GRCh38-v1.6 scores without annotation

Header: '##CADD GRCh38-v1.6 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health 2013-2020. All rights reserved.'

Version: v1.6
GenomeBuild: GRCh38
Annotation: false


CADD_workdir: /mnt/vol009/hg38_vep105/CADD-scripts

# File parameter
PrescoredFolder: /mnt/vol009/hg38_vep105/CADD-scripts/data/prescored/GRCh38_v1.6/no_anno
ReferenceConfig: configs/references_GRCh38_v1.6.cfg
ImputeConfig: configs/impute_GRCh38_v1.6.cfg
Model: /mnt/vol009/hg38_vep105/CADD-scripts/data/models/GRCh38/CADDv1.6-GRCh38.mod
ConversionTable: /mnt/vol009/hg38_vep105/CADD-scripts/data/models/GRCh38/conversionTable_CADDv1.6-GRCh38.txt

# VEP
VEPpath: /mnt/vol009/hg38_vep105/CADD-scripts/data/annotations/GRCh38_v1.6/vep
EnsemblDB: 95

Columns: '1-4,133,134'
